spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_social_network?options=-c%20TimeZone=Europe/Kyiv
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: ${EMAIL_HOSTNAME}
    port: 465
    username: ${EMAIL_USER_NAME}
    password: ${EMAIL_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: smtp.gmail.com
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  application:
    security:
      jwt:
        secret-key: MmMyNzQzMjE4NjYzMjUyNjMwMDM2OTc5YmFjOTNhMWI=
        expiration: 86400000
    mailing:
      frontend:
        activation-url: http://localhost:4200/activate-account
    cors:
      origins: http://localhost:4200,http://localhost:8080,http://192.168.0.227:8088,http://192.168.0.227:8080
    file:
      uploads:
        photos-output-path: ./uploads
server:
  port: 8088
